### ISSUE TITLE
Issues in output.

### ISSUE THREAD

**Issue by veeranaveens** [saikatharryc/judge0_helm#6]
When I am trying to add a new base image(judge0/judge0) instead of judge0/api. Everything works fine but in stdout response return null for all the languages. Even there is no error stderr also null.
Did I need to change any other things in it?

PFB - Sample output
`"language_id": 46,
 "stdout": null,
 "status_id": 1,
 "stderr": null,
 "token": "372cf134-2b24-4643-82b9-3678d8163c35"`

**Comment by saikatharryc** [comment]
@naveen-veera I do not maintain this anymore, if you use or plan to do so, feel free to raise PR!
(I'm a bit outdated with the changes at the moment Judge0 have)

**Comment by veeranaveens** [comment]
@saikatharryc Thanks for the update.
